# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aiursoft-tracer = {
    pname = "aiursoft-tracer";
    version = "957a13a7db61822e06e7a4a151e890225fb91605";
    src = fetchFromGitHub {
      owner = "Anduin2017";
      repo = "Tracer";
      rev = "957a13a7db61822e06e7a4a151e890225fb91605";
      fetchSubmodules = false;
      sha256 = "sha256-M3sJXXlEebdHRZbGqhV7k+5siHWLf1RrHwBrsxFfHaU=";
    };
    date = "2024-08-22";
  };
}
